function normalizeSection(value) {
  return typeof value === "string" ? value.trim() : "";
}

function formatDate(date) {
  return new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function buildPrintableHtml(sections, routerDecision, domainLabel, date) {
  const title = "CARDO Decision Report";
  const sectionBlocks = [
    ["Hinge", sections?.Hinge],
    ["Facts", sections?.Facts],
    ["Assumptions", sections?.Assumptions],
    ["Evaluation", sections?.Evaluation],
    ["What Would Change This", sections?.ChangeMind],
    ["Recommended Move", sections?.Move],
  ]
    .filter(([, text]) => Boolean(text && text.trim()))
    .map(([label, text]) => `
      <section style="margin-bottom: 24px;">
        <h2 style="margin: 0 0 8px; font-size: 18px;">${label}</h2>
        <div style="white-space: pre-wrap; line-height: 1.5;">${text}</div>
      </section>
    `)
    .join("");

  const routerLine = routerDecision
    ? `<p><strong>Router:</strong> ${routerDecision.label} (${routerDecision.model})</p>`
    : "";

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${title}</title>
    <style>
      body { font-family: Arial, sans-serif; color: #111827; margin: 24px; line-height: 1.5; }
      h1 { margin-bottom: 8px; }
      .meta { color: #4b5563; margin-bottom: 24px; }
      @media print { body { margin: 0; } }
    </style>
  </head>
  <body>
    <h1>${title}</h1>
    <div class="meta">
      <p><strong>Generated:</strong> ${date}</p>
      <p><strong>Domain:</strong> ${domainLabel}</p>
      ${routerLine}
    </div>
    ${sectionBlocks}
    <hr />
    <p style="color: #6b7280;">Generated by REI.ai — CARDO methodology</p>
  </body>
</html>`;
}

export function buildDecisionReport({ sections = {}, routerDecision, domainLabel = "REI.ai", sourceText = "", createdAt = new Date() }) {
  const normalizedSections = {
    Hinge: normalizeSection(sections?.Hinge),
    Facts: normalizeSection(sections?.Facts),
    Assumptions: normalizeSection(sections?.Assumptions),
    Evaluation: normalizeSection(sections?.Evaluation),
    ChangeMind: normalizeSection(sections?.ChangeMind),
    Move: normalizeSection(sections?.Move),
    intro: normalizeSection(sections?.intro),
  };

  const dateText = formatDate(createdAt);
  const filename = `cardo-decision-${Date.now()}.md`;

  const markdown = [
    "# CARDO Decision Report",
    "",
    `**Generated:** ${dateText}`,
    `**Domain:** ${domainLabel}`,
    routerDecision ? `**Router:** ${routerDecision.label} (${routerDecision.model})` : "",
    "",
    normalizedSections.intro ? `## Introduction\n${normalizedSections.intro}\n` : "",
    normalizedSections.Hinge ? `## Hinge\n${normalizedSections.Hinge}\n` : "",
    normalizedSections.Facts ? `## Facts\n${normalizedSections.Facts}\n` : "",
    normalizedSections.Assumptions ? `## Assumptions\n${normalizedSections.Assumptions}\n` : "",
    normalizedSections.Evaluation ? `## Evaluation\n${normalizedSections.Evaluation}\n` : "",
    normalizedSections.ChangeMind ? `## What Would Change This\n${normalizedSections.ChangeMind}\n` : "",
    normalizedSections.Move ? `## Recommended Move\n${normalizedSections.Move}\n` : "",
    sourceText ? `## Source Message\n${sourceText}\n` : "",
    "",
    "---",
    "*Generated by REI.ai — CARDO methodology*",
  ]
    .filter(Boolean)
    .join("\n");

  return {
    filename,
    markdown,
    html: buildPrintableHtml(normalizedSections, routerDecision, domainLabel, dateText),
  };
}
