/**
 * buildDecisionReport — CARDO decision document generator
 *
 * Takes a parsed CARDO result (sections + router metadata)
 * and returns a timestamped .md file ready for download.
 *
 * v1 scope: markdown file download only.
 * No dependencies. No PDF generation. No print HTML.
 */

/**
 * @param {Object} sections — parsed CARDO sections { Hinge, Facts, Assumptions, Evaluation, ChangeMind, Move, intro }
 * @param {Object} metadata — { domainLabel, routerDecision, timestamp }
 * @returns {{ filename: string, markdown: string }}
 */
export function buildDecisionReport(sections = {}, metadata = {}) {
  const { domainLabel = "", routerDecision = {}, timestamp = "" } = metadata;

  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines = [
    "# CARDO Decision Report",
    "",
    `**Generated:** ${date}`,
    domainLabel && `**Domain:** ${domainLabel}`,
    routerDecision?.label && `**Router:** ${routerDecision.label}`,
    routerDecision?.model && `**Model:** ${routerDecision.model}`,
    routerDecision?.estimatedCost != null &&
      `**Estimated cost:** $${routerDecision.estimatedCost.toFixed(4)}`,
    timestamp && `**Session:** ${timestamp}`,
    "",
    "---",
    "",
  ];

  const sectionOrder = [
    { key: "Hinge", label: "Hinge", prefix: "📌" },
    { key: "Facts", label: "Facts", prefix: "🔬" },
    { key: "Assumptions", label: "Assumptions", prefix: "❓" },
    { key: "Evaluation", label: "Evaluation & Risk", prefix: "⚖️" },
    { key: "ChangeMind", label: "What Would Change This", prefix: "🔄" },
    { key: "Move", label: "Recommended Move", prefix: "🚀" },
  ];

  for (const section of sectionOrder) {
    const content = sections[section.key];
    if (content && content.trim()) {
      lines.push(`## ${section.prefix} ${section.label}`, "", content, "");
    }
  }

  lines.push("---", "", "*Generated by REI.ai — CARDO methodology*", "");

  return {
    filename: `cardo-decision-${Date.now()}.md`,
    markdown: lines.filter(Boolean).join("\n"),
  };
}

export function buildDefaultFileName() {
  return `cardo-decision-${Date.now()}.md`;
}
